<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="FB_Pump" Id="{c4f79673-c352-48af-9b2c-c649dc4f25ab}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_Pump EXTENDS StateMachineBase IMPLEMENTS I_HydrualicPump
VAR_INPUT
    bIsSimulator : BOOL;
	bPumpRelay : BOOL; // Option: has pump with relay only
	bPumpHPU : BOOL; // Option: has Hydrualic Power Unit (HPU)
END_VAR
VAR_OUTPUT
END_VAR
VAR
    //fInputSignal : LREAL;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="getSignal" Id="{4b31f716-6658-43ef-a156-6de609a15d27}">
      <Declaration><![CDATA[METHOD getSignal : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="start" Id="{85ca6983-27bb-4c44-9760-8f51e66523f4}">
      <Declaration><![CDATA[METHOD start : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[nextState := eState_Startup;]]></ST>
      </Implementation>
    </Method>
    <Method Name="stop" Id="{8ac0dd21-6534-45b4-911c-e5607e880992}">
      <Declaration><![CDATA[METHOD stop : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[nextState := eState_Stopping;]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="FB_Pump">
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="FB_Pump.getSignal">
      <LineId Id="5" Count="0" />
    </LineIds>
    <LineIds Name="FB_Pump.start">
      <LineId Id="5" Count="0" />
    </LineIds>
    <LineIds Name="FB_Pump.stop">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>