<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="FB_SomeGrantryRobot" Id="{8623795a-912a-40c2-a294-dc497aee4ac5}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_SomeGrantryRobot
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="FB_SomeGrantryRobot">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>