<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="FB_Fanuc" Id="{12ac1ec7-c492-4001-99fb-5b6278171b1a}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_Fanuc
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="FB_Fanuc">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>