<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="FB_Kuka_KRC2" Id="{a64a119b-0352-4618-9447-2528436fe8a6}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_Kuka_KRC2
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="FB_Kuka_KRC2">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>